### ISSUE TITLE
Issues running code with stock data

### ISSUE THREAD

**Issue by skxliu** [mnemesure/linchpin_centrality#1]
Was encountering issues running linchpin.centrality with my own data, so I tried to run it with the exact data frames in the write-up. 

Still encountering issues around line 48:
"> traceback()
3: stop("nothing to tabulate")
2: table(ids_full) at #48
1: Linchpin.CentralityTest(links = edgelisttest, characteristics = characteristicstest, 
       label_column_name = "Specialty", weighted = FALSE, char_subset = c("empty"))"

This could be entirely user error on my end, but I was wondering if you would be willing to share a sample dataset that the function works on?

**Comment by mnemesure** [comment]
Happy to share sample data but I think I know what the issue might be. I accidentally made a small part of this slightly inflexible that I am happy to fix in a new push. Essentially the column that contains ID in the characteristics data set must be labeled "ID_1" 

Let me know if that fixes things but I will also make a new push fixing that issue.

**Comment by mnemesure** [comment]
```
N_unique_actors=100
N_sim_edges = 1000
N_unique_chars = 50

edge1 = sample(x=seq(1,N_unique_actors),size=N_sim_edges,replace = T)
edge2 = sample(x=seq(1,N_unique_actors),size=N_sim_edges,replace = T)
edge_list = matrix(data=NA,nrow=N_sim_edges, ncol=2)
edge_list[,1]=edge1
edge_list[,2]=edge2
edge_list = data.frame(edge_list)

attributes = matrix(data=NA,nrow=N_unique_actors, ncol=2)
attributes[,1] = seq(1,N_unique_actors)
attributes[,2] = sample(sprintf("char%s",seq(1,50)),N_unique_actors, replace=T)

atts = data.frame(attributes)
colnames(atts) = c('ID_1', 'label')

atts$ID_1=as.numeric(atts$ID_1)

final_output = Linchpin.Centrality(links=edge_list, characteristics = atts, label_column_name = 'label')
```

**Comment by skxliu** [comment]
The ID_1 change worked and I was able to run the code with my own data -- thank you so much!
