### ISSUE TITLE
Subsetting Question

### ISSUE THREAD

**Issue by skxliu** [mnemesure/linchpin_centrality#2]
Any chance you know why the subset function works with one characteristic but not multiple?

Returning "Error in if (char_subset != c("empty")) { : the condition has length > 1" when I try to use multiple.

Thank you for the help!

**Comment by mnemesure** [comment]
Can you paste in how you are calling the function? I'm getting a warning message because of the way R handles vectors in if statements but it still appears to be working for me. 

Here's how I called it.

Linchpin.Centrality(links=edge, characteristics = char, label_column_name = 'spspec', char_subset= c('gp', 'surg'))

**Comment by skxliu** [comment]
Linchpin.Centrality(links = top11edges, characteristics = top11nodes2, label_column_name = 'modularity_class', weighted = FALSE, char_subset = c('87','86','89'))

where 87, 86, 89 are modularity classes saved as factors - it works with individual classes, which I thought was odd

**Comment by mnemesure** [comment]
try converting modularity class to characters instead of factors. 

`top11nodes2$modularity_class = as.character(top11nodes2$modularity_class)`

**Comment by skxliu** [comment]
Still giving "Error in if (char_subset != c("empty")) { : the condition has length > 1" unfortunately. 

No worries if you aren't sure -- I can double check my data/brute force the subset

**Comment by mnemesure** [comment]
wonder if its an R version thing. I get a similar warning but no error message. Im using 4.0.2. Essentially all the subset is doing is updating the values not in the subset to be 'NAN'. The easiest solution would be to just do that outside the function and then ignore the subset argument. 

```non_important_inds = which(!(top11nodes2[,'modularity_class'] %in% c('87','86','89'))```
```copy_top11nodes2 = top11nodes2```
```copy_top11nodes2[non_important_inds,'modularity_class'] = 'NAN'```

```Linchpin.Centrality(links = top11edges, characteristics = copy_top11nodes2, label_column_name = 'modularity_class', weighted = FALSE,)```

**Comment by skxliu** [comment]
Could be -- I'm running 4.2.2. 

Running the function outside works though. Thank you so much for the help!
